spring:
  mongodb:
    uri: ${MONGO_URI}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    paasword: guest

management:
  endpoints:
    include: "busrefresh"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8082
