spring:
  mongodb:
    uri: ${MONGO_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timeout: 30000

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh,prometheus"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8082

keycloak:
  admin:
    username: user
    password: user
    server-url: http://localhost:8443
    realm: ecom_app
    client-id: admin-cli
    client-uid: 507cda94-5d37-4ae3-a83b-65f592ea48d3